/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ModFile = IDL.Record({
  'content' : IDL.Vec(IDL.Nat8),
  'contentType' : IDL.Text,
  'filename' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ModData = IDL.Record({
  'id' : IDL.Text,
  'files' : IDL.Vec(ModFile),
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'description' : IDL.Text,
  'version' : IDL.Text,
  'gameName' : IDL.Text,
  'prompt' : IDL.Text,
  'unlistedId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMod' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ModFile),
        IDL.Text,
      ],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMod' : IDL.Func([IDL.Text], [ModData], ['query']),
  'getModByUnlistedId' : IDL.Func([IDL.Text], [ModData], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listModFiles' : IDL.Func([IDL.Text], [IDL.Vec(ModFile)], ['query']),
  'listModsForCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ModData)],
      ['query'],
    ),
  'listModsForGame' : IDL.Func([IDL.Text], [IDL.Vec(ModData)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateModFiles' : IDL.Func([IDL.Text, IDL.Vec(ModFile)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ModFile = IDL.Record({
    'content' : IDL.Vec(IDL.Nat8),
    'contentType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ModData = IDL.Record({
    'id' : IDL.Text,
    'files' : IDL.Vec(ModFile),
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'description' : IDL.Text,
    'version' : IDL.Text,
    'gameName' : IDL.Text,
    'prompt' : IDL.Text,
    'unlistedId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMod' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ModFile),
          IDL.Text,
        ],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMod' : IDL.Func([IDL.Text], [ModData], ['query']),
    'getModByUnlistedId' : IDL.Func([IDL.Text], [ModData], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listModFiles' : IDL.Func([IDL.Text], [IDL.Vec(ModFile)], ['query']),
    'listModsForCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ModData)],
        ['query'],
      ),
    'listModsForGame' : IDL.Func([IDL.Text], [IDL.Vec(ModData)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateModFiles' : IDL.Func([IDL.Text, IDL.Vec(ModFile)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };