/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ModData {
  'id' : string,
  'files' : Array<ModFile>,
  'title' : string,
  'creator' : Principal,
  'description' : string,
  'version' : string,
  'enabled' : boolean,
  'gameName' : string,
  'prompt' : string,
  'unlistedId' : string,
}
export interface ModFile {
  'content' : Uint8Array,
  'contentType' : string,
  'filename' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMod' : ActorMethod<
    [string, string, string, string, string, string, Array<ModFile>, string],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMod' : ActorMethod<[string], ModData>,
  'getModByUnlistedId' : ActorMethod<[string], ModData>,
  'getModEnabledState' : ActorMethod<[string], boolean>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listModFiles' : ActorMethod<[string], Array<ModFile>>,
  'listModsForCreator' : ActorMethod<[Principal], Array<ModData>>,
  'listModsForGame' : ActorMethod<[string], Array<ModData>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setModEnabledState' : ActorMethod<[string, boolean], undefined>,
  'updateModFiles' : ActorMethod<[string, Array<ModFile>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];